Repository codeit-sprint-part3-5Bit/part3-project, pull requests merged in 2024-09, with the labels that each got.

#7 Feat : 퀴즈 모달 컴포넌트
  next.config.mjs
  src/components/wiki/QuizModal.tsx
Labels: 새로운 기능 추가

#18 Feat : icon 이미지추가
  public/assets/Icons/AlarmIcon_Big.svg
  public/assets/Icons/AlarmIcon_small.svg
  public/assets/Icons/AlignIcon.svg
  public/assets/Icons/ArrowIcon.svg
  public/assets/Icons/BoldIcon.svg
  public/assets/Icons/BulletIcon.svg
  public/assets/Icons/CameraIcon.svg
  public/assets/Icons/CheckIcon.svg
  public/assets/Icons/DeleteIcon.svg
  public/assets/Icons/ExclamationIcon.svg
  public/assets/Icons/ExpandIcon.svg
  public/assets/Icons/HamburgerIcon.svg
  public/assets/Icons/HeartIcon.svg
  public/assets/Icons/ImageIcon.svg
  public/assets/Icons/InfoIcon.svg
  public/assets/Icons/ItalicIcon.svg
  public/assets/Icons/LinkIcon.svg
  public/assets/Icons/MagnifierIcon.svg
  public/assets/Icons/NumberIcon.svg
  public/assets/Icons/PenIcon.svg
  public/assets/Icons/ProfileIcon.svg
  public/assets/Icons/UnderlineIcon.svg
  public/assets/Icons/VideoIcon.svg
  public/assets/Icons/closeicon.svg
  public/assets/Icons/lockicon.svg
Labels: 새로운 기능 추가

#22 Feat: 이미지모달컴포넌트추가
  package-lock.json
  package.json
  src/components/wiki/ImageModal.tsx
Labels: 새로운 기능 추가

#23 Fix: 커스텀버튼 타입지정
  src/components/wiki/ImageModal.tsx
Labels: 버그수정

#24 Feat: Nav컴포넌트추가
  src/components/Nav.tsx
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 새로운 기능 추가

#26 Feat wikipage startpage
  next.config.mjs
  package-lock.json
  package.json
  public/assets/Icons/CheckIcon.svg
  public/assets/Icons/LinkIcon.svg
  public/assets/image/Lendinf_GreenW.svg
  public/assets/image/defaultImage.png
  src/apis/profile.tsx
  src/components/Nav.tsx
  src/components/wiki/QuizModal.tsx
  src/components/wiki/Snackbar.tsx
  src/lib/axios.tsx
  src/pages/_app.tsx
  src/pages/wiki/[code].tsx
  src/types/wiki.ts
Labels: 새로운 기능 추가

#35 Feat 게시글목록페이지 검색기능 수정작업
  public/assets/Icons/defaultImage.png
  src/components/Nav.tsx
  src/components/common/ImageModal.tsx
  src/pages/articles/create.tsx
  src/pages/board/[articleId].tsx
  src/pages/board/edit/[articleId].tsx
  src/pages/board/index.tsx
  src/pages/index.tsx
Labels: 버그수정, 새로운 기능 추가

#36 Feat: 글작성 컴포넌트 추가
  public/assets/Icons/AlignIcon_center.svg
  public/assets/Icons/Alignment_left.svg
  public/assets/Icons/Alignment_right.svg
  public/assets/Icons/Font.svg
  src/components/ContentWriter.tsx
Labels: 도움!!!, 새로운 기능 추가

#38 feat-위키프로필 리스트 페이지 구현
  package-lock.json
  package.json
  src/components/Nav.tsx
  src/components/wikiList/ProfileList.tsx
  src/components/wikiList/SearchForm.tsx
  src/pages/wikiList/index.tsx
Labels: 새로운 기능 추가

#37 feat : 로그인 API, 토큰, 로컬스토리지 구현
  src/apis/base.ts
  src/apis/login/login.ts
  src/utils/localStorage/localStorage.ts
  src/utils/token/renewTokens.ts
  src/utils/token/token.ts
Labels: 새로운 기능 추가

#39 Feat: 게시글에디터 수정, 게시글상세페이지 ui수정작업
  package-lock.json
  package.json
  src/components/ContentWriter.tsx
  src/pages/articles/create.tsx
  src/pages/board/index.tsx
  src/styles/globals.css
Labels: 버그수정, 새로운 기능 추가

#41 Fix : navbar 버튼 경로 지정
  public/assets/Icons/searchicon.svg
  src/components/Nav.tsx
  src/components/wikiList/ProfileList.tsx
  src/components/wikiList/SearchForm.tsx
  src/pages/index.tsx
  src/pages/wikiList/index.tsx
Labels: 새로운 기능 추가

#43 Feat: 메인렌딩페이지추가
  public/assets/image/Lending_Logo.svg
  src/pages/MainLanding.tsx
Labels: 새로운 기능 추가

#45 feat: 목록페이지와 상세페이지 연동
  src/pages/board/index.tsx
Labels: 새로운 기능 추가

#46 feat : 계정 설정 페이지 구현
  src/pages/AccountSet/index.tsx
Labels: 새로운 기능 추가

#47 fix : 메인 렌딩페이지 추가 및 리팩토링
  package-lock.json
  package.json
  src/components/mainpage/MainLanding.tsx
  src/components/wikiList/SearchForm.tsx
  src/pages/MainLanding.tsx
  src/pages/index.tsx
  src/pages/wikiList/index.tsx
Labels: 버그수정

#50 feat : 로그인 컴포넌트 수정
  src/apis/register/register.ts
  src/components/common/authButton.tsx
  src/components/common/authInput.tsx
  src/components/login/loginForm.tsx
Labels: 새로운 기능 추가

#52 fix : 랜딩 페이지 버튼 로직 수정
  src/components/Nav.tsx
  src/components/context/AuthContext.tsx
  src/components/login/loginForm.tsx
  src/components/mainpage/MainLanding.tsx
  src/pages/AccountSet/index.tsx
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/wiki/[code].tsx
Labels: 버그수정

#54 Fix landingpage v2
  src/components/login/loginForm.tsx
  src/components/mainpage/MainLanding.tsx
  src/components/register/signupForm.tsx
  src/pages/AccountSet/index.tsx
Labels: 버그수정

#55 feat : wiki 페이지 로직 구현
  next.config.mjs
  package-lock.json
  package.json
  public/assets/Icons/coloringIcon.svg
  src/apis/profile.tsx
  src/components/common/customInput.tsx
  src/components/wiki/BlockingModal.tsx
  src/components/wiki/QuizModal.tsx
  src/components/wiki/WarningModal.tsx
  src/components/wiki/profileContentArea/index.tsx
  src/components/wiki/profileContentArea/textEditor/index.tsx
  src/components/wiki/profileContentArea/textEditor/media/index.tsx
  src/components/wiki/profileContentArea/textEditor/toolBar/index.tsx
  src/components/wiki/profileContentArea/textEditor/toolBar/toolBarComponents/colorSelector.tsx
  src/components/wiki/profileContentArea/textEditor/toolBar/toolBarComponents/headingDropdown.tsx
  src/components/wiki/profileContentArea/textEditor/toolBar/toolBarComponents/imageUpload.tsx
  src/components/wiki/profileHeader/index.tsx
  src/components/wiki/sideProfile/OriginalProfile/index.tsx
  src/components/wiki/sideProfile/index.tsx
  src/components/wiki/wikiModal/Modals/BlockingModal.tsx
  src/components/wiki/wikiModal/Modals/QuizModal.tsx
  src/components/wiki/wikiModal/index.tsx
  src/pages/_app.tsx
  src/pages/wiki/[code].tsx
  src/styles/globals.css
  src/types/wiki.ts
  tailwind.config.ts
Labels: 새로운 기능 추가

#57 Feat-api변경, 로그인 토큰 및 그에따른 작업
  package-lock.json
  package.json
  src/components/ContentWriter.tsx
  src/components/common/ImageModal.tsx
  src/pages/articles/create.tsx
  src/pages/board/[articleId].tsx
  src/pages/board/edit/[articleId].tsx
  src/pages/board/index.tsx
Labels: 버그수정, 새로운 기능 추가

#56 feat : wiki 페이지 버그 수정, 알람 기능 구현, Nav바 수정
  public/assets/Icons/BigProfileIcon.svg
  public/assets/image/NoNotification.svg
  src/apis/notificationListApi/index.tsx
  src/components/AlarmMenu/elapsedTimeConverter/index.tsx
  src/components/AlarmMenu/index.tsx
  src/components/AlarmMenu/noNotificationImg/index.tsx
  src/components/AlarmMenu/notificationList/index.tsx
  src/components/AlarmMenu/useNotificationList/index.tsx
  src/components/AlarmMenu/useOutsideClick/index.tsx
  src/components/Nav.tsx
  src/components/context/AuthContext.tsx
  src/components/wiki/profileContentArea/textEditor/index.tsx
  src/components/wiki/profileHeader/index.tsx
  src/components/wiki/sideProfile/index.tsx
  src/components/wikiList/SearchForm.tsx
  src/types/notificationType/index.tsx
Labels: 버그수정, 새로운 기능 추가
